####################################################################################
# Application Information
####################################################################################

app_name: javawebapp
artifact_name: "{{ app_name }}.war"

####################################################################################
# Tomcat Configuration
####################################################################################

tomcat_service: tomcat
tomcat_home: /home/tomcat/current
tomcat_webapps: "{{ tomcat_home }}/webapps"

####################################################################################
# Backup Configuration
####################################################################################

backup_dir: /home/tomcat/backups

####################################################################################
# Artifact Configuration
####################################################################################

artifact_download_dir: /opt/deployment/tomcat-war-deployment/artifacts

####################################################################################
# Health Check
####################################################################################

health_check_retries: 10
health_check_delay: 5

####################################################################################
# Checksum
####################################################################################

checksum_algorithm: sha256

####################################################################################
# Nexus Credentials
####################################################################################
nexus_username: admin
nexus_password: $Shrin@th@025
